name: reactive_exploration
description: Reactive Flutter apps

dependencies:
  rxdart: ^0.19.0
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  scoped_model: ^0.3.0
  flutter_redux: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true